---
- hosts: all
  become: yes
  tasks:
  - name: "Installing webserver"
    package:
      name: "{{package_name}}"
      state: present
  - name: "Update debian machine"
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: "Update Redhat machine"
    yum:
      update_Cache: yes
    when: ansible_os_family == "Redhat"
  - name: "Installing utilities"
    package:
      name: "{{item}}"
      state: present
   # with_item: utilities
    with_item:
    - git
    - tree
    - nano
    when: ansible_os_family == 'Redhat'



# ansible-playbook -i "inventory/hosts" web.yaml
