---
- hosts: all
  become: yes
  tasks:
  - name: Update apt package
    apt:
      update_cache: yes
# Nodejs specific settings
# install nodejs from
# https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-16-04#how-to-install-using-a-ppa
- hosts: app
  become: yes
  vars:
    folderpath: /home/ansible/nodesetup
    appserverport: 8080
  tasks:
  - name: Creating nodesetup directory
    file:
      path: "{{folderpath}}"
      state: directory
      mode: 0755
  - name: Download nodejs package setup
    command: "curl -sL https://deb.nodesource.com/setup_8.x -o {{folderpath}}/nodesource_setup.sh"
  - name: Execute downloaded shell script
    command: "sudo bash {{folderpath}}/nodesource_setup.sh"
  - name: install nodejs
    apt:
      name: nodejs
      state: present
  - name: copy the file
    template:
      src: "templates/hello.js.j2"
      dest: "{{ folderpath }}/hello.js"
  - name: Install pm2
    npm:
      name: cofee-script
      global: yes
  - name: start nodejs apps
    command: "npm start {{ folderpath }}/hello.js "

- hosts: web
  become: yes
  vars:
    webserver_dns_name: "ec2-13-59-188-102.us-east-2.compute.amazonaws.com"
    appserver_ip: 172.31.45.208
  tasks:
  - name: install nginx
    apt:
      name: nginx
      state: present
  - name: copy default file
    template:
      src: templates/default.j2
      dest: /etc/nginx/sites-available/default
    notify: Restart Nginx
  handlers:
  - name: Restart Nginx
    service:
      name: nginx
      state: restarted
  